version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - docker images
      - docker run -d -p 8000:8000 --name helloworld_container helloworld
      - sleep 10
      - docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' helloworld_container
      - curl http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' helloworld_container):8000