version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - docker images
      - docker run -d -p 8000:8000 helloworld
      - sleep 10
      - curl http://localhost:8000